### ISSUE TITLE
Ponies does not work in HTTPS.

### ISSUE THREAD

**Issue by patriksvensson** [panzi/Browser-Ponies#5]
As a user,
I want ponies in all the sites,
so that I can stay happy.

**Comment by panzi** [comment]
Yeah, sadly this seems not to be possible with GitHub pages. Hosting browser ponies somewhere else is not possible, because the last time I did it gave me about 10 GB traffic a day, which is just not payable for me for such a hobby project. I don't make any money with this (and I think I never could, because of Hasbro's copyright and all).

So this is a `wontfix` (or `cantfix` rather).

But you can always download it all and host it yourself. It's all static content (JavaScript, image and audio files).
